apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-claude-staging
  namespace: anthology-ai-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-claude-ui-staging
  template:
    metadata:
      labels:
        app: super-claude-ui-staging
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: us-west1-b
      containers:
        - name: super-claude-ui
          image: gcr.io/api-for-warp-drive/super-claude-ui:staging
          ports:
            - containerPort: 8080
          env:
            - name: API_ENDPOINT
              value: "https://us-west4-c.api-for-warp-drive.cloudfunctions.net/super-claude-staging"
            - name: VISION_LAKE_BUCKET
              value: "vision-lake-staging"
            - name: RAY_HOST
              value: "ray-instance.us-west4-c.c.api-for-warp-drive.internal"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"